services:
  cloner:
    image: aleixmt/repo-updater:latest
    container_name: repo-updater
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN  # Needed or the connections through the VPN never succeed
    devices:
      - /dev/ppp  # Needed or the connections through the VPN never succeed
    volumes:
      - ./data:/data
      - ./repos:/repos
      - ./logs:/var/log
    secrets:
      - urv_user
      - urv_pass
      - vpn_gateway
      - vpn_realm
      - vpn_port
      - vpn_trusted_cert
      - git_server
    #entrypoint: /git_clone.exp <DNI> <GIT_SERVER_BEHIND_FORTINET_VPN> <REPO_NAME> /repos/my-project <PASS>"

secrets:
  urv_user:
    file: secrets/URV_USER
  urv_pass:
    file: secrets/URV_PASSWORD
  vpn_realm:
    file: secrets/VPN_REALM
  vpn_gateway:
    file: ./secrets/VPN_GATEWAY
  vpn_port:
    file: ./secrets/VPN_PORT
  vpn_trusted_cert:
    file: ./secrets/VPN_TRUSTED_CERT
  git_server:
    file: ./secrets/GIT_SERVER