#!/usr/bin/expect -f

# Arguments: <user> <server> <repo_path> <target_dir> <password>
set timeout -1
set user [lindex $argv 0]
set server [lindex $argv 1]
set repo [lindex $argv 2]
set target [lindex $argv 3]
set password [lindex $argv 4]

spawn git clone --verbose "$user@$server:$repo" "$target"

expect {
    -re "$user@$server's password:" {
        send "$password\r"
        exp_continue
    }
    eof
}


